### ISSUE TITLE
Impersonal enchantment should rotate player to face target after teleport

### ISSUE THREAD

**Issue by FewerFlaws** [Tigereye504/spellbound#4]
Right now it's a bit odd trying to fight something when you're constantly forced to look away from it.  Impersonal feels like a curse.  It would be an improvement if the teleport rotated you to face the target when placing you behind them.

**Comment by Tigereye504** [comment]
This idea was originally rejected because it would be almost impossible to counter an opponent that spammed impersonal attacks to stay perpetually behind you, and facing was a way to limit such spam. However, as a cooldown is being added to impersonal for similar balance reasons I no longer have any reason to refuse.

This should be implemented in the next update.
