### ISSUE TITLE
[Bug] Jousting enchantment on weapon causes it to appear as if it's on cooldown

### ISSUE THREAD

**Issue by Derpitron** [Tigereye504/spellbound#9]
![image](https://user-images.githubusercontent.com/46134462/120887818-a41ce480-c612-11eb-8597-fe801e96e924.png)

I have enchanted a sword as in the image. It appears like the sword is being held down, like the attack cooldown, but it doesn't come back up. If I left click with the sword it swings and the tip of the sword can be seen, showing that the sword appears like it's on cooldown. 

As soon as i switch to the sword it appears for a second then gets pulled down.

I am not sure if this is intentional or not.

The only mods I had while testing were Fabric API and Spellbound Enchantments 1.3.0

**Comment by Tigereye504** [comment]
It is an unwanted consequence of frequently updating a jousting weapon's nbt data, which in turn is a workaround for servers being unaware of an entity's velocity when they are grounded. It is a known issue, but as it is a purely visual and low priority issue it will remain unaddressed until a better solution to the underlying problem is found.

**Comment by Derpitron** [comment]
Oh I see, thank you for the clarification
